-- MySQL Script generated by MySQL Workbench
-- Sat Nov 18 12:33:30 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Users` (
  `idUsers` INT NOT NULL AUTO_INCREMENT,
  `Users_email` VARCHAR(45) NULL,
  `User_first_name` VARCHAR(45) NULL,
  `User_last_name` VARCHAR(45) NULL,
  PRIMARY KEY (`idUsers`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Products` (
  `idProducts` INT NOT NULL AUTO_INCREMENT,
  `Product_name` VARCHAR(45) NULL,
  `Product_price` VARCHAR(45) NULL,
  `Product_qty` INT NULL,
  `File_name` VARCHAR(45) NULL,
  PRIMARY KEY (`idProducts`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Downloads`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Downloads` (
  `idDownloads` INT NOT NULL AUTO_INCREMENT,
  `File_name` VARCHAR(45) NULL,
  `File_date` VARCHAR(45) NULL,
  `idUsers` INT NULL,
  `Users_idUsers` INT NOT NULL,
  `Products_idProducts` INT NOT NULL,
  PRIMARY KEY (`idDownloads`),
  INDEX `fk_Downloads_Users_idx` (`Users_idUsers` ASC),
  INDEX `fk_Downloads_Products1_idx` (`Products_idProducts` ASC),
  CONSTRAINT `fk_Downloads_Users`
    FOREIGN KEY (`Users_idUsers`)
    REFERENCES `mydb`.`Users` (`idUsers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Downloads_Products1`
    FOREIGN KEY (`Products_idProducts`)
    REFERENCES `mydb`.`Products` (`idProducts`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
